###

GET http://localhost:9000/api/cate

###

POST http://localhost:9000/api/cate
Content-Type: application/json

{
    "cateName" : "Huwtsas"
}


###

DELETE http://localhost:9000/api/cate/8bb91107-0f70-473a-af04-87baf39b94d8

###

PUT http://localhost:9000/api/cate
Content-Type: application/json 

{
    "id":"6864627a-c016-4d79-9d96-4a2ae8b3b1ba",
    "cateName" : "Mongol Deel"
}
