###

GET http://localhost:9000/api/product

###

POST http://localhost:9000/api/product
Content-Type: application/json

{
    "title" : "Shoes",
    "description" : "Super Grey",
    "price" : "200,000₮",
    "rating":"6.99",
    "brand":"America",
    "category": "Shoes",
    "image":"https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8c2hvZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60"
}

###

DELETE http://localhost:9000/api/product/5b51c517-3191-4be3-b22b-e09e10e3cbfc

###

PUT http://localhost:9000/api/product
Content-Type: application/json 

{

}
